# Generated by Django 3.2.7 on 2021-09-15 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_job_jobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
    ]
