# Generated by Django 3.2.7 on 2021-09-15 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210915_0307'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='detail',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
