# Generated by Django 3.2.7 on 2021-09-15 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_tile_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tile',
            old_name='summary',
            new_name='company',
        ),
    ]
