# Generated by Django 3.2.7 on 2021-09-15 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_summary_tile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='detail',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
