# Generated by Django 3.2.7 on 2021-09-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_tile_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='tile',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
