# Generated by Django 3.2.7 on 2021-09-15 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_tile_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tile',
            name='company',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
